<template>
  <v-layout
    row
    v-once>
    <v-flex xs12>
      <h2>Data Privacy Policy</h2>
      <p>
        Our website may be used without entering personal information. Different rules may apply to certain services on
        our site, however, and are explained separately below. We collect personal information from you (e.g. name,
        address, email address, telephone number, etc.) in accordance with the provisions of German data protection
        statutes. Information is considered personal if it can be associated exclusively to a specific natural person.
        The legal framework for data protection may be found in the German Federal Data Protection Act (BDSG) and the
        Telemedia Act (TMG). The provisions below serve to provide information as to the manner, extent and purpose for
        collecting, using and processing personal information by the provider.
      </p>
      <p>
        <strong>
          Sylvia Bär<br>
          Photoleuchten<br>
          76137 Karlsruhe<br>
          Germany
        </strong>
      </p>
      <p>
        <strong>
          E-Mail: photoleuchten@yahoo.com
        </strong>
      </p>
      <p>
        Please be aware that data transfer via the internet is subject to security risks and, therefore, complete
        protection against third-party access to transferred data cannot be ensured.
      </p>

      <h4>Contacting Us</h4>
      <p>
        On our website we offer you the opportunity to contact us, either by email and/or by using a contact form. In
        such event, information provided by the user is stored for the purpose of facilitating communications with the
        user. No data is transferred to third parties. Nor is any of this information matched to any information that
        may be collected by other components of our website.
      </p>

      <h4>Use of Google Analytics with anonymization</h4>
      <p>
        Our website uses Google Analytics, a web analysis service from Google Inc., 1600 Amphitheatre Parkway, Mountain
        View, CA 94043 USA, hereinafter referred to as “Google“. Google Analytics employs so-called “cookies“, text
        files that are stored to your computer in order to facilitate an analysis of your use of the site.
      </p>
      <p>
        The information generated by these cookies, such as time, place and frequency of your visits to our site,
        including your IP address, is transmitted to Google’s location in the US and stored there.
      </p>
      <p>
        We use Google Analytics with an IP anonymization feature on our website. In doing so, Google abbreviates and
        thereby anonymizes your IP address before transferring it from member states of the European Union or signatory
        states to the Agreement on the European Economic Area.
      </p>
      <p>
        Google will use this information to evaluate your usage of our site, to compile reports on website activity for
        us, and to provide other services related to website-&nbsp;and internet usage. Google may also transfer this
        information to third parties if this is required by law or to the extent this data is processed by third parties&nbsp;on
        Google´s behalf.
      </p>
      <p>
        Google states that it will in never associate your IP address with other data held by Google. You can prevent
        cookies from being installed by adjusting the settings on your browser software accordingly. You should be
        aware, however, that by doing so you may not be able to make full use of all the functions of our website.
      </p>
      <p>
        Google also offers a disabling option for the most common browsers, thus providing you with greater control
        over&nbsp;the data which is collected and processed by Google. If you enable this option, no information
        regarding your website visit is transmitted to Google Analytics. However, the activation does not prevent the
        transmission of information to us or to any other web analytics services we may use. For more information about
        the disabling option provided by Google, and how to enable this option, visit
        <a
          href="https://tools.google.com/dlpage/gaoptout?hl=de"
          target="_blank"
          rel="nofollow">https://tools.google.com/dlpage/gaoptout?hl=en
        </a>
      </p>

      <h3>Information/Cancellation/Deletion</h3>
      <p>
        On the basis of the Federal Data Protection Act, you may contact us at no cost if you have questions relating
        to the collection, processing or use of your personal information, if you wish to request the correction,
        blocking or deletion of the same, or if you wish to cancel explicitly granted consent. Please note that you have
        the right to have incorrect data corrected or to have personal data deleted, where such claim is not barred by
        any legal obligation to retain this data.
      </p>
      <p>
        <a
          href="https://www.ratgeberrecht.eu/leistungen/muster-datenschutzerklaerung.html"
          target="_blank">Sample Data
          Privacy Policy Statement
        </a> provided by the
        <a
          href="https://www.ratgeberrecht.eu/"
          target="_blank">Law Offices
          of Weiß &amp; Partner</a>
      </p>
    </v-flex>
  </v-layout>
</template>

<script>
  export default {}
</script>
